# ══════════════════════════════════════════════════════════════════════════════
# HUGO BLOX CONFIGURATION
# Schema: hugoblox.com/schema/v2
# Tutorial: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# ══════════════════════════════════════════════════════════════════════════════
hugoblox:
  schema: "2.0"

  # IDENTITY
  identity:
    name: "Ethan Feilich's Personal Website"
    organization: ""
    type: person 
    tagline: "Personal website of Ethan Feilich"
    description: "Personal website of Ethan Feilich"

  # THEME
  theme:
    mode: system
    pack: "default"
    colors:
      primary: "indigo" 
      secondary: "indigo"
      neutral: "" 

 # TYPOGRAPHY
  typography:
    font: "sans"
    size: "md"

  # LAYOUT
  layout:
    radius: "none"
    spacing: compact
    avatar_shape: circle 

  # HEADER
  header:
    enable: true
    style: navbar
    sticky: true
    align: right
    search: false
    theme_toggle: true
    theme_picker: false
    language_switcher: false

  # FOOTER
  footer:
    style: minimal 
    language_switcher: false
    text: ""

  # COPYRIGHT
  copyright:
    notice: "© {year} {name}. This work is licensed under {license}"
    license:
      type: cc
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

  # SEO
  seo:
    ai:
      allow: []
      disallow: [ "*" ]
      note: "Crawlers are asked not to access this site."

  # CONTENT
  content:
    math:
      enable: true
    toc:
      enable: true
    reading_time:
      enable: true
    citations:
      style: apa

  # SEARCH
  #search:
  #  enable: false
  #  suggestions: []
  #  quick_actions: []

  # REPOSITORY
  repository:
    enable: false
    url: "" # e.g., https://github.com/efeilich/efeilich.github.io
    branch: main
    content_dir: content

  # LOCALE
  locale:
    date_format: "2006-01-02" # Go time format
    time_format: "15:04"
    address_format: en-us

  # DEBUG
  debug:
    enable: false
    hud:
      position: bottom-left # top-left | top-right | bottom-left | bottom-right
      opacity: 1.0
    export_logs: true

  # PREMIUM
  i_am_a_sponsor: true
